# Generated by Django 2.1.5 on 2020-01-30 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plague', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.IntegerField(choices=[(1, 'Symptoms'), (2, 'Sickness')])),
            ],
        ),
        migrations.CreateModel(
            name='PlaguePointer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=1000)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('prescription', models.TextField(max_length=1000)),
                ('informer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plague.Informer')),
                ('keyword_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plague.KeywordTag')),
            ],
        ),
    ]
