# Generated by Django 2.1.5 on 2020-01-30 01:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plague', '0003_plaguepointerkeyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plaguepointerkeyword',
            name='trust_level',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
