# Generated by Django 2.2.2 on 2020-02-06 13:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('plague', '0004_auto_20200130_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informer',
            name='api_key',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
